#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libgd
Version  : 2.3.3
Release  : 43
URL      : https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.xz
Source0  : https://github.com/libgd/libgd/releases/download/gd-2.3.3/libgd-2.3.3.tar.xz
Summary  : GD graphics library
Group    : Development/Tools
License  : MIT
Requires: libgd-bin = %{version}-%{release}
Requires: libgd-lib = %{version}-%{release}
Requires: libgd-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : buildreq-cmake
BuildRequires : fontconfig-dev
BuildRequires : gettext-bin
BuildRequires : libavif-dev
BuildRequires : liberation-fonts
BuildRequires : libjpeg-turbo-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : libwebp-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(xpm)
BuildRequires : zlib-dev
Patch1: 0001-Revert-Fix-318-these-macros-are-not-used-as-planed-w.patch
Patch2: 0002-add-comment-to-not-remove-these-macros.patch
Patch3: 0003-install-missing-header-used-by-gdpp.h.patch

%description
GD Graphics (Draw) Library. GD is an open source code library for the dynamic
creation of images by programmers. GD is written in C, and "wrappers" are
available for Perl, PHP and other languages. GD can read and write many
different image formats. GD is commonly used to generate charts, graphics,
thumbnails, and most anything else, on the fly.

%package bin
Summary: bin components for the libgd package.
Group: Binaries
Requires: libgd-license = %{version}-%{release}

%description bin
bin components for the libgd package.


%package dev
Summary: dev components for the libgd package.
Group: Development
Requires: libgd-lib = %{version}-%{release}
Requires: libgd-bin = %{version}-%{release}
Provides: libgd-devel = %{version}-%{release}
Requires: libgd = %{version}-%{release}

%description dev
dev components for the libgd package.


%package lib
Summary: lib components for the libgd package.
Group: Libraries
Requires: libgd-license = %{version}-%{release}

%description lib
lib components for the libgd package.


%package license
Summary: license components for the libgd package.
Group: Default

%description license
license components for the libgd package.


%prep
%setup -q -n libgd-2.3.3
cd %{_builddir}/libgd-2.3.3
%patch1 -p1
%patch2 -p1
%patch3 -p1

%build
## build_prepend content
aclocal && automake
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1632348114
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export FCFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export FFLAGS="$FFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -fzero-call-used-regs=used "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
# Export TMP to fix some tests... adapted from Arch Linux package
TMP=$(mktemp -d) make V=1 VERBOSE=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1632348114
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libgd
cp %{_builddir}/libgd-2.3.3/COPYING %{buildroot}/usr/share/package-licenses/libgd/6f8207620999c02672110df88dfd165619deff88
cp %{_builddir}/libgd-2.3.3/docs/naturaldocs/html/files/license-txt.html %{buildroot}/usr/share/package-licenses/libgd/40affaf28a3dd2183da771a09d1837c8b300a4a3
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/annotate
/usr/bin/bdftogd
/usr/bin/gd2copypal
/usr/bin/gd2togif
/usr/bin/gd2topng
/usr/bin/gdcmpgif
/usr/bin/gdparttopng
/usr/bin/gdtopng
/usr/bin/giftogd2
/usr/bin/pngtogd
/usr/bin/pngtogd2
/usr/bin/webpng

%files dev
%defattr(-,root,root,-)
/usr/include/gd.h
/usr/include/gd_color_map.h
/usr/include/gd_errors.h
/usr/include/gd_io.h
/usr/include/gd_io_stream.h
/usr/include/gdcache.h
/usr/include/gdfontg.h
/usr/include/gdfontl.h
/usr/include/gdfontmb.h
/usr/include/gdfonts.h
/usr/include/gdfontt.h
/usr/include/gdfx.h
/usr/include/gdpp.h
/usr/lib64/libgd.so
/usr/lib64/pkgconfig/gdlib.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgd.so.3
/usr/lib64/libgd.so.3.0.11

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libgd/40affaf28a3dd2183da771a09d1837c8b300a4a3
/usr/share/package-licenses/libgd/6f8207620999c02672110df88dfd165619deff88
